const STEPS = [
  // ── Chapter 1: Basics ────────────────────────────────────────
  {
    id: 'WELCOME',
    chapter: 1,
    bubble: {
      text: 'أهلاً يا شبل! 🦁 سأعلّمك اللعبة خطوة بخطوة',
      pos: 'center',
    },
    spot: null,
    arrow: null,
    trigger: 'TAP_ANYWHERE',
    autoDelay: null,
    ruleCard: null,
    isPractice: false,
    isReward: false,
  },
  {
    id: 'SHOW_HAND',
    chapter: 1,
    bubble: {
      text: 'هذه بطاقتك 🃏 كل لاعب يمسك بطاقة واحدة',
      pos: 'bottom',
    },
    spot: 'hand-card',
    arrow: null,
    trigger: 'TAP_ANYWHERE',
    autoDelay: null,
    ruleCard: null,
    isPractice: false,
    isReward: false,
  },
  {
    id: 'DRAW_CARD',
    chapter: 1,
    bubble: {
      text: 'اسحب بطاقة من الكومة 👇 اضغط عليها الآن!',
      pos: 'center',
    },
    spot: 'deck',
    arrow: 'deck',
    trigger: 'TAP_DECK',
    autoDelay: null,
    ruleCard: null,
    isPractice: false,
    isReward: false,
  },
  {
    id: 'TWO_CARDS',
    chapter: 1,
    bubble: {
      text: 'رائع! 🎉 الآن معك بطاقتان — اختر واحدة للعب',
      pos: 'bottom',
    },
    spot: 'hand-area',
    arrow: null,
    trigger: 'TAP_ANYWHERE',
    autoDelay: null,
    ruleCard: null,
    isPractice: false,
    isReward: false,
  },
  {
    id: 'SELECT_CARD',
    chapter: 1,
    bubble: {
      text: 'اضغط على البطاقة المُضيئة لتختارها 👆',
      pos: 'bottom',
    },
    spot: 'hand-card',
    arrow: 'hand-card',
    trigger: 'TAP_HAND',
    autoDelay: null,
    ruleCard: null,
    isPractice: false,
    isReward: false,
  },
  {
    id: 'PLAY_CARD',
    chapter: 1,
    bubble: {
      text: 'ممتاز! اضغط عليها مرة ثانية للعبها 🎮',
      pos: 'bottom',
    },
    spot: 'hand-card',
    arrow: 'hand-card',
    trigger: 'TAP_PLAY',
    autoDelay: null,
    ruleCard: null,
    isPractice: false,
    isReward: false,
  },
  {
    id: 'SEE_RESULT',
    chapter: 1,
    bubble: {
      text: 'انظر ماذا حدث! 👀 ثم اضغط حسناً',
      pos: 'center',
    },
    spot: null,
    arrow: 'confirm',
    trigger: 'TAP_CONFIRM',
    autoDelay: null,
    ruleCard: null,
    isPractice: false,
    isReward: false,
  },
  // ── Chapter 2: Special rules ──────────────────────────────────
  {
    id: 'TEACH_CARD1',
    chapter: 2,
    bubble: {
      text: 'كرت المقهى ☕ خمّن كرت خصمك — لو أصبت يخرج من اللعبة!',
      pos: 'bottom',
    },
    spot: null,
    arrow: null,
    trigger: 'TAP_ANYWHERE',
    autoDelay: null,
    ruleCard: { id: 1 },
    isPractice: false,
    isReward: false,
  },
  {
    id: 'TEACH_CARD4',
    chapter: 2,
    bubble: {
      text: 'كرت الجارة 🛡️ يحميك! لا أحد يقدر يؤثر فيك حتى دورك القادم',
      pos: 'bottom',
    },
    spot: null,
    arrow: null,
    trigger: 'TAP_ANYWHERE',
    autoDelay: null,
    ruleCard: { id: 4 },
    isPractice: false,
    isReward: false,
  },
  {
    id: 'TEACH_CARD7',
    chapter: 2,
    bubble: {
      text: '⚠️ لو معك كرت البستان مع 5 أو 6 لازم تلعب البستان أولاً!',
      pos: 'bottom',
    },
    spot: null,
    arrow: null,
    trigger: 'TAP_ANYWHERE',
    autoDelay: null,
    ruleCard: { id: 7 },
    isPractice: false,
    isReward: false,
  },
  {
    id: 'TEACH_CARD8',
    chapter: 2,
    bubble: {
      text: 'خطر! ⭐ نجمة الحي — لو خرجت من يدك لأي سبب تخرج أنت!',
      pos: 'bottom',
    },
    spot: null,
    arrow: null,
    trigger: 'TAP_ANYWHERE',
    autoDelay: null,
    ruleCard: { id: 8 },
    isPractice: false,
    isReward: false,
  },
  // ── Chapter 3: Practice ───────────────────────────────────────
  {
    id: 'PRACTICE',
    chapter: 3,
    bubble: {
      text: 'الآن نجرب معاً! 🎮 العب دوراً بمساعدتي',
      pos: 'center',
    },
    spot: null,
    arrow: null,
    trigger: 'TAP_ANYWHERE',
    autoDelay: null,
    ruleCard: null,
    isPractice: true,
    isReward: false,
  },
  {
    id: 'REWARD',
    chapter: 3,
    bubble: {
      text: 'أحسنت يا شبل! 🏆',
      pos: 'center',
    },
    spot: null,
    arrow: null,
    trigger: 'AUTO',
    autoDelay: 0,
    ruleCard: null,
    isPractice: false,
    isReward: true,
  },
];

export default STEPS;
