export const BUILDINGS = {
  house: {
    id: 'house',
    nameAr: 'بيت',
    category: 'residential',
    emoji: '🏠',
    buildCost: 30000,
    maintenancePerMonth: 500,
    capacity: 4,
    incomeType: 'rent',
    baseRentPerResident: 400,
    sellValueMultiplier: 0.85,
    effectRadius: 0,
    satisfactionBonus: 0,
    pollutionRadius: 0,
    pollutionPenalty: 0,
    description: 'مسكن متواضع يستوعب عائلة صغيرة',
  },
  apartment: {
    id: 'apartment',
    nameAr: 'شقة',
    category: 'residential',
    emoji: '🏢',
    buildCost: 80000,
    maintenancePerMonth: 1200,
    capacity: 20,
    incomeType: 'rent',
    baseRentPerResident: 350,
    sellValueMultiplier: 0.80,
    effectRadius: 0,
    satisfactionBonus: 0,
    pollutionRadius: 0,
    pollutionPenalty: 0,
    description: 'مبنى سكني متعدد الطوابق',
  },
  villa: {
    id: 'villa',
    nameAr: 'فيلا',
    category: 'residential',
    emoji: '🏡',
    buildCost: 120000,
    maintenancePerMonth: 2000,
    capacity: 8,
    incomeType: 'rent',
    baseRentPerResident: 800,
    sellValueMultiplier: 0.90,
    effectRadius: 0,
    satisfactionBonus: 0,
    pollutionRadius: 0,
    pollutionPenalty: 0,
    description: 'سكن فاخر للعائلات الميسورة',
  },
  restaurant: {
    id: 'restaurant',
    nameAr: 'مطعم',
    category: 'commercial',
    emoji: '🍽️',
    buildCost: 50000,
    maintenancePerMonth: 800,
    capacity: 0,
    incomeType: 'monthly',
    monthlyIncome: 4000,
    incomeScaleWithPop: true,
    popIncomeScale: 0.01,
    sellValueMultiplier: 0.75,
    effectRadius: 2,
    satisfactionBonus: 5,
    pollutionRadius: 1,
    pollutionPenalty: 2,
    description: 'يوفر الطعام ويرفع رضا السكان القريبين',
  },
  shop: {
    id: 'shop',
    nameAr: 'محل',
    category: 'commercial',
    emoji: '🏪',
    buildCost: 25000,
    maintenancePerMonth: 400,
    capacity: 0,
    incomeType: 'monthly',
    monthlyIncome: 2000,
    incomeScaleWithPop: true,
    popIncomeScale: 0.008,
    sellValueMultiplier: 0.75,
    effectRadius: 2,
    satisfactionBonus: 3,
    pollutionRadius: 0,
    pollutionPenalty: 0,
    description: 'محل تجاري صغير يخدم الحي',
  },
  mall: {
    id: 'mall',
    nameAr: 'مركز تسوق',
    category: 'commercial',
    emoji: '🏬',
    buildCost: 200000,
    maintenancePerMonth: 5000,
    capacity: 0,
    incomeType: 'monthly',
    monthlyIncome: 18000,
    incomeScaleWithPop: true,
    popIncomeScale: 0.02,
    sellValueMultiplier: 0.70,
    effectRadius: 4,
    satisfactionBonus: 12,
    pollutionRadius: 2,
    pollutionPenalty: 4,
    description: 'مجمع تجاري ضخم يجذب السكان من كل مكان',
  },
  park: {
    id: 'park',
    nameAr: 'حديقة',
    category: 'service',
    emoji: '🌳',
    buildCost: 15000,
    maintenancePerMonth: 600,
    capacity: 0,
    incomeType: 'none',
    monthlyIncome: 0,
    sellValueMultiplier: 0.60,
    effectRadius: 3,
    satisfactionBonus: 15,
    pollutionRadius: 0,
    pollutionPenalty: 0,
    description: 'حديقة عامة ترفع رضا السكان في المنطقة المحيطة',
  },
  mosque: {
    id: 'mosque',
    nameAr: 'مسجد',
    category: 'service',
    emoji: '🕌',
    buildCost: 40000,
    maintenancePerMonth: 800,
    capacity: 0,
    incomeType: 'none',
    monthlyIncome: 0,
    sellValueMultiplier: 0.50,
    effectRadius: 4,
    satisfactionBonus: 20,
    pollutionRadius: 0,
    pollutionPenalty: 0,
    description: 'يرفع الرضا والطمأنينة لدى السكان في نطاق واسع',
  },
  school: {
    id: 'school',
    nameAr: 'مدرسة',
    category: 'service',
    emoji: '🏫',
    buildCost: 60000,
    maintenancePerMonth: 1500,
    capacity: 0,
    incomeType: 'none',
    monthlyIncome: 0,
    sellValueMultiplier: 0.55,
    effectRadius: 3,
    satisfactionBonus: 18,
    pollutionRadius: 0,
    pollutionPenalty: 0,
    description: 'توفير التعليم يجذب العائلات ويرفع رضاهم',
  },
  factory: {
    id: 'factory',
    nameAr: 'مصنع',
    category: 'industrial',
    emoji: '🏭',
    buildCost: 100000,
    maintenancePerMonth: 3000,
    capacity: 0,
    incomeType: 'monthly',
    monthlyIncome: 15000,
    incomeScaleWithPop: false,
    sellValueMultiplier: 0.65,
    effectRadius: 0,
    satisfactionBonus: 0,
    pollutionRadius: 4,
    pollutionPenalty: 25,
    description: 'دخل مرتفع لكنه يلوث البيئة ويضر بالسكان القريبين',
  },
  warehouse: {
    id: 'warehouse',
    nameAr: 'مستودع',
    category: 'industrial',
    emoji: '🏗️',
    buildCost: 40000,
    maintenancePerMonth: 800,
    capacity: 0,
    incomeType: 'monthly',
    monthlyIncome: 4500,
    incomeScaleWithPop: false,
    sellValueMultiplier: 0.70,
    effectRadius: 0,
    satisfactionBonus: 0,
    pollutionRadius: 2,
    pollutionPenalty: 8,
    description: 'دخل ثابت مع تلوث بسيط للمنطقة المحيطة',
  },
};

export const BUILDING_CATEGORIES = {
  residential: { nameAr: 'سكني',   emoji: '🏘️', color: '#4CAF50' },
  commercial:  { nameAr: 'تجاري',  emoji: '🛍️', color: '#2196F3' },
  service:     { nameAr: 'خدمات',  emoji: '🌿', color: '#9C27B0' },
  industrial:  { nameAr: 'صناعي',  emoji: '⚙️', color: '#FF5722' },
};

export const BUILDING_ORDER = [
  'house', 'apartment', 'villa',
  'restaurant', 'shop', 'mall',
  'park', 'mosque', 'school',
  'factory', 'warehouse',
];
