export const STORY_MESSAGES = [
  {
    id: 'intro',
    trigger: { type: 'month', value: 1 },
    character: 'advisor',
    nameAr: 'المستشار سعيد',
    emoji: '👴',
    textAr: 'مرحباً يا صاحب السمو، هذه الأرض الخالية أمانة في عنقك. ابنِ البيوت أولاً، واجذب السكان. بدونهم لا مدينة.',
  },
  {
    id: 'first_building',
    trigger: { type: 'buildingCount', value: 1 },
    character: 'engineer',
    nameAr: 'المهندس خالد',
    emoji: '👷',
    textAr: 'ممتاز! البنية الأولى جاهزة. أنصحك بتأجيرها للحصول على دخل شهري ثابت. البيع سريع لكن الإيجار أفضل على المدى البعيد.',
  },
  {
    id: 'first_residents',
    trigger: { type: 'population', value: 10 },
    character: 'citizen',
    nameAr: 'المواطنة أم فيصل',
    emoji: '👩',
    textAr: 'شكراً لك يا أميرنا على هذا البيت الجميل! لكن أطفالنا يحتاجون مدرسة، وقلوبنا تشتاق لمسجد قريب.',
  },
  {
    id: 'economy_tip',
    trigger: { type: 'month', value: 6 },
    character: 'merchant',
    nameAr: 'التاجر أبو ناصر',
    emoji: '💼',
    textAr: 'لو بنيت محلاً أو مطعماً قربي، سيزيد دخلك ويزيد رضا السكان معاً. التجارة تُحيي الأحياء يا سموّ الأمير!',
  },
  {
    id: 'pollution_warning',
    trigger: { type: 'satisfactionDrop', value: 35 },
    character: 'citizen',
    nameAr: 'المواطنة أم فيصل',
    emoji: '👩',
    textAr: 'الدخان يخنقنا يا أميرنا! المصانع قريبة جداً من بيوتنا. إذا استمر هذا، سنضطر للرحيل.',
  },
  {
    id: 'halfway',
    trigger: { type: 'month', value: 24 },
    character: 'advisor',
    nameAr: 'المستشار سعيد',
    emoji: '👴',
    textAr: 'مرّت سنتان يا سموّ الأمير. المدينة تنمو لكن الهدف لم يكتمل بعد. ركّز على الخدمات — الحدائق والمدارس تجلب الأسر.',
  },
  {
    id: 'near_win',
    trigger: { type: 'populationPercent', value: 80 },
    character: 'engineer',
    nameAr: 'المهندس خالد',
    emoji: '👷',
    textAr: 'نحن قريبون من الهدف! المدينة باتت حقيقية. بضعة مبانٍ إضافية وستنتهي مهمتك بنجاح.',
  },
  {
    id: 'bankruptcy_warning',
    trigger: { type: 'budgetThreshold', value: 20000 },
    character: 'advisor',
    nameAr: 'المستشار سعيد',
    emoji: '👴',
    textAr: 'تحذير يا سموّ الأمير! خزينة المدينة تكاد تفرغ. بع بعض المباني أو خفّض المصاريف قبل فوات الأوان!',
  },
];
